version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: chatting-postgres
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    volumes:
      - chatting_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: chatting-redis
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: chatting-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - chatting_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  redisinsight:
    image: redis/redisinsight:latest
    container_name: chatting-redisinsight
    ports:
      - "5540:5540"
    volumes:
      - chatting_redisinsight_data:/data
    depends_on:
      - redis

volumes:
  chatting_postgres_data:
  chatting_pgadmin_data:
  chatting_redisinsight_data:
